language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction

script: php -d hhvm.resource_limit.socket_default_timeout=12 vendor/bin/phpunit

cache:
  directories:
  - $HOME/.composer/cache/

sudo: false

git:
  depth: 1
